### ISSUE TITLE
Start Coming up with Style for Webpage

### ISSUE THREAD

**Issue by hpache** [hpache/SignLanguageWebsite#3]
# Part 2 for Project Development

Pretty self explanatory, start coming up with ideas for the style. We should ideally be thinking about this while doing the wireframe, but it doesn't hurt to come up with some design ideas during the first part of the development phase.

**DONT COME UP WITH A CSS FILE, JUST DRAW UP SOME DESIGNS**

**Comment by hpache** [comment]
Add a photo of your layout idea here:

https://github.com/hpache/SignLanguageWebsite/wiki/Project-Documentation

**Comment by ryancurry1122** [comment]
I actually like the design. Should I make a CSS for it?

**Comment by hpache** [comment]
Like make your own css? > I actually like the design. Should I make a CSS for it?
